deploymentMode: SingleBinary

# Desabilitar componentes SimpleScalable
read:
  replicas: 0

write:
  replicas: 0

backend:
  replicas: 0

# Gateway desabilitado (usar ingress direto)
gateway:
  replicas: 0

singleBinary:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

  extraEnv:
    - name: GOMEMLIMIT
      value: "400MiB"
    - name: GOGC
      value: "100"

  securityContext:
    runAsNonRoot: true
    runAsUser: 10001
    runAsGroup: 10001
    fsGroup: 10001

  persistence:
    enabled: true
    size: 5Gi
    storageClass: longhorn

# INGRESS GLOBAL - APENAS UMA SEÇÃO
ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  hosts:
    - host: loki.rancher.pointertech.digital
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: loki-tls
      hosts:
        - loki.rancher.pointertech.digital

# Desabilitar caches explicitamente
chunksCache:
  enabled: false
  replicas: 0

resultsCache:
  enabled: false
  replicas: 0

indexGateway:
  enabled: false
  replicas: 0

loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1

  storage:
    type: s3
    bucketNames:
      chunks: loki
      ruler: loki
      admin: loki
    s3:
      endpoint: https://minio.rancher.pointertech.digital
      region: us-east-1
      accessKeyId: z6Nwkpk3HD84fwLcGmfzx6giN5NA3XH5slg5tTaBRdvGv7LHLKHwwKYaAWaRZCHB
      secretAccessKey: W7HEkWlJfGFjllSil9JMwjqYfxyidwxVpJdkCTIZE2H8nkynelW5RxDzf1VZUdMr
      s3ForcePathStyle: true
      insecure: false

  schemaConfig:
    configs:
      - from: 2024-01-01
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h

  limits_config:
    volume_enabled: true
    retention_period: 168h

    # Rate Limits simplificados
    ingestion_rate_mb: 10
    ingestion_burst_size_mb: 20
    per_stream_rate_limit: 3MB
    per_stream_rate_limit_burst: 5MB

    # Stream Limits
    max_global_streams_per_user: 5000
    max_streams_per_user: 0

    # Structured Metadata
    allow_structured_metadata: false

    # Logs antigos - Aceitar
    reject_old_samples: false
    reject_old_samples_max_age: 168h

    # Configurações simplificadas
    unordered_writes: true
    creation_grace_period: 10m

    # Query/Line Limits
    max_line_size: 256KB
    max_entries_limit_per_query: 5000
    max_query_parallelism: 8
    max_query_series: 500

  compactor:
    retention_enabled: true
    working_directory: /tmp/loki/compactor
    compaction_interval: 10m
    retention_delete_delay: 2h
    retention_delete_worker_count: 150

  server:
    http_listen_port: 3100
    http_server_read_timeout: 30s
    http_server_write_timeout: 30s

# SEÇÕES OBRIGATÓRIAS - DESABILITAR COMPONENTES DESNECESSÁRIOS
prometheus:
  enabled: false

alertmanager:
  enabled: false

grafana:
  enabled: false

promtail:
  enabled: false

monitoring:
  dashboards:
    enabled: false
  rules:
    enabled: false
  serviceMonitor:
    enabled: false

test:
  enabled: false